# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALr5cxYNJm6CE5GqH1HxpI-fnckZOv8M
"""

# ================================================================
# EXPERIMENT 7 - PULSE SHAPING AND THE NYQUIST CRITERION
# Digital Communication Laboratory
#
# Rectangular, Sinc, Raised Cosine (RC) and
# Root Raised Cosine (RRC) pulses
# ================================================================

import numpy as np
import matplotlib.pyplot as plt

# Close previous figures
plt.close('all')

# ================================================================
# 1. GLOBAL PARAMETERS
# ================================================================

Ts = 1.0                    # Symbol period
sps = 16                    # Samples per symbol
Fs = sps / Ts              # Sampling frequency
span = 8                    # Filter span in symbols
alphas = [0, 0.25, 0.5, 1] # Roll-off factors

# Time vector
t = np.arange(-span * Ts, span * Ts + 1/Fs, 1/Fs)

print("================================================")
print("EXPERIMENT 7 - PULSE SHAPING")
print("================================================")
print(f"Ts = {Ts} s")
print(f"Fs = {Fs} Hz")
print(f"Samples per symbol = {sps}")
print(f"Filter span = +/- {span} symbols")
print("================================================")


# ================================================================
# 2. RECTANGULAR PULSE
# ================================================================

rect_pulse = (np.abs(t) <= Ts/2).astype(float)


# ================================================================
# 3. SINC PULSE
# ================================================================

# np.sinc(x) = sin(pi*x)/(pi*x)
sinc_pulse = np.sinc(t / Ts)


# ================================================================
# 4. RAISED COSINE FUNCTION
# ================================================================

def raised_cosine(t, Ts, alpha):

    t = np.asarray(t, dtype=float)

    h = np.zeros_like(t)

    if alpha == 0:

        h = np.sinc(t / Ts)

    else:

        # Normal RC equation
        denominator = 1 - (2 * alpha * t / Ts)**2

        # Normal case
        normal = np.abs(denominator) > 1e-10

        x = np.pi * t / Ts

        h[normal] = (
            np.sin(x[normal]) / x[normal]
            * np.cos(np.pi * alpha * t[normal] / Ts)
            / denominator[normal]
        )

        # t = 0
        zero = np.abs(t) < 1e-10
        h[zero] = 1.0

        # t = +/- Ts/(2*alpha)
        singular = (
            np.abs(np.abs(2 * alpha * t / Ts) - 1)
            < 1e-10
        )

        h[singular] = (
            alpha / 2
            * np.sin(np.pi / (2 * alpha))
        )

    return h


# ================================================================
# 5. ROOT RAISED COSINE FUNCTION
# ================================================================

def root_raised_cosine(t, Ts, alpha):

    t = np.asarray(t, dtype=float)

    h = np.zeros_like(t)

    if alpha == 0:

        h = np.sinc(t / Ts) / np.sqrt(Ts)

    else:

        # Normal RRC equation
        numerator = (
            np.sin(
                np.pi * t / Ts * (1 - alpha)
            )
            +
            4 * alpha * t / Ts
            *
            np.cos(
                np.pi * t / Ts * (1 + alpha)
            )
        )

        denominator = (
            np.pi * t / Ts
            *
            (1 - (4 * alpha * t / Ts)**2)
        )

        # Normal points
        normal = (
            (np.abs(t) > 1e-10)
            &
            (np.abs(np.abs(4 * alpha * t / Ts) - 1)
             > 1e-10)
        )

        h[normal] = (
            numerator[normal]
            /
            denominator[normal]
            /
            np.sqrt(Ts)
        )

        # t = 0
        zero = np.abs(t) < 1e-10

        h[zero] = (
            (1 / np.sqrt(Ts))
            *
            (1 - alpha + 4 * alpha / np.pi)
        )

        # t = +/- Ts/(4*alpha)
        singular = (
            (np.abs(t) > 1e-10)
            &
            (
                np.abs(
                    np.abs(4 * alpha * t / Ts) - 1
                ) < 1e-10
            )
        )

        a = alpha

        h[singular] = (
            a / np.sqrt(2 * Ts)
            *
            (
                (1 + 2/np.pi)
                * np.sin(np.pi/(4*a))
                +
                (1 - 2/np.pi)
                * np.cos(np.pi/(4*a))
            )
        )

    return h


# ================================================================
# 6. GENERATE RC AND RRC PULSES
# ================================================================

RC = []
RRC = []

for alpha in alphas:

    RC.append(
        raised_cosine(t, Ts, alpha)
    )

    RRC.append(
        root_raised_cosine(t, Ts, alpha)
    )

RC = np.array(RC)
RRC = np.array(RRC)


# ================================================================
# 7. PLOT RAISED COSINE PULSES
# ================================================================

plt.figure(figsize=(10, 6))

for i, alpha in enumerate(alphas):

    plt.plot(
        t / Ts,
        RC[i],
        linewidth=1.5,
        label=f'α = {alpha}'
    )

plt.axhline(0, linewidth=0.7)
plt.xlabel('t / Ts')
plt.ylabel('hRC(t)')
plt.title('Raised-Cosine Pulse for Different Roll-Off Factors')
plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 8. PLOT ROOT RAISED COSINE PULSES
# ================================================================

plt.figure(figsize=(10, 6))

for i, alpha in enumerate(alphas):

    plt.plot(
        t / Ts,
        RRC[i],
        linewidth=1.5,
        label=f'α = {alpha}'
    )

plt.axhline(0, linewidth=0.7)
plt.xlabel('t / Ts')
plt.ylabel('hRRC(t)')
plt.title('Root Raised-Cosine Pulse for Different Roll-Off Factors')
plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 9. RECTANGULAR VS SINC VS RC VS RRC
# ================================================================

alpha_test = 0.5

index_alpha = alphas.index(alpha_test)

rc_test = RC[index_alpha]
rrc_test = RRC[index_alpha]

# Normalize RRC for visual comparison
rrc_normalized = rrc_test / np.max(np.abs(rrc_test))


plt.figure(figsize=(11, 6))

plt.plot(
    t / Ts,
    rect_pulse,
    linewidth=1.3,
    label='Rectangular'
)

plt.plot(
    t / Ts,
    sinc_pulse,
    linewidth=1.3,
    label='Sinc (Ideal Nyquist)'
)

plt.plot(
    t / Ts,
    rc_test,
    linewidth=1.5,
    label='RC, α = 0.5'
)

plt.plot(
    t / Ts,
    rrc_normalized,
    linewidth=1.5,
    label='RRC, α = 0.5 (Normalized)'
)

plt.xlabel('t / Ts')
plt.ylabel('Amplitude')
plt.title('Rectangular vs Sinc vs RC vs RRC')
plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 10. FREQUENCY RESPONSE OF RC
# ================================================================

Nfft = 8192

f = (
    np.arange(-Nfft/2, Nfft/2)
    * (Fs / Nfft)
)

plt.figure(figsize=(11, 6))

for i, alpha in enumerate(alphas):

    H = np.fft.fftshift(
        np.fft.fft(RC[i], Nfft)
    )

    H = np.abs(H)

    H = H / np.max(H)

    plt.plot(
        f * Ts,
        H,
        linewidth=1.5,
        label=f'α = {alpha}'
    )

plt.xlim([-1.2, 1.2])

plt.xlabel('f × Ts')
plt.ylabel('|H(f)|')
plt.title('Raised-Cosine Frequency Response')
plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 11. FREQUENCY RESPONSE OF RRC
# ================================================================

plt.figure(figsize=(11, 6))

for i, alpha in enumerate(alphas):

    H = np.fft.fftshift(
        np.fft.fft(RRC[i], Nfft)
    )

    H = np.abs(H)

    H = H / np.max(H)

    plt.plot(
        f * Ts,
        H,
        linewidth=1.5,
        label=f'α = {alpha}'
    )

plt.xlim([-1.2, 1.2])

plt.xlabel('f × Ts')
plt.ylabel('|H_RRC(f)|')
plt.title('Root Raised-Cosine Frequency Response')
plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 12. GENERATE RANDOM BPSK SYMBOLS
# ================================================================

Nsyms = 20

np.random.seed(1)

symbols = (
    2 * np.random.randint(0, 2, Nsyms)
    - 1
)

# Upsampled impulse train
impulse_train = np.zeros(Nsyms * sps)

impulse_train[::sps] = symbols

print("\nRandom BPSK symbols:")
print(symbols)


# ================================================================
# 13. RC PULSE SHAPING
# ================================================================

h_rc = rc_test.copy()

# Normalize peak
h_rc = h_rc / np.max(np.abs(h_rc))

# Convolution
shaped = np.convolve(
    impulse_train,
    h_rc
)

# Filter delay
delay = span * sps


# ================================================================
# 14. PLOT PULSE-SHAPED BPSK SIGNAL
# ================================================================

plt.figure(figsize=(12, 6))

plt.stem(
    np.arange(len(impulse_train)),
    impulse_train,
    linefmt='C0-',
    markerfmt='C0o',
    basefmt=' ',
    label='Symbol impulses'
)

plt.plot(
    np.arange(len(shaped)) - delay,
    shaped,
    linewidth=1.3,
    label='RC pulse-shaped signal'
)

plt.xlim([0, Nsyms * sps])

plt.xlabel('Sample Index')
plt.ylabel('Amplitude')

plt.title(
    'RC Pulse-Shaped BPSK Signal, α = 0.5'
)

plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 15. NYQUIST ZERO-CROSSING VERIFICATION
# ================================================================

n_check = np.arange(-5, 6)

t_check = n_check * Ts

h_at_symbols = raised_cosine(
    t_check,
    Ts,
    alpha_test
)

# Normalize h(0) = 1
h_at_symbols = (
    h_at_symbols
    / h_at_symbols[n_check == 0][0]
)


print("\n")
print("================================================")
print("NYQUIST ZERO-CROSSING VERIFICATION")
print("================================================")
print(f"RC roll-off factor α = {alpha_test}")
print("------------------------------------------------")
print(" n        t/Ts        h(nTs)")
print("------------------------------------------------")

for n, time_value, value in zip(
    n_check,
    t_check,
    h_at_symbols
):

    print(
        f"{n:3d}      {time_value/Ts:5.1f}      {value:+.6f}"
    )


nonzero = n_check != 0

max_sidelobe = np.max(
    np.abs(h_at_symbols[nonzero])
)

print("------------------------------------------------")
print("Expected:")
print("h(0) = 1")
print("h(nTs) = 0 for n != 0")

print(
    f"\nMaximum sidelobe at non-zero symbol instants = "
    f"{max_sidelobe:.3e}"
)


# ================================================================
# 16. RRC TRANSMITTER + RRC RECEIVER
# ================================================================

h_rrc = rrc_test.copy()

# Normalize
h_rrc = h_rrc / np.max(np.abs(h_rrc))

# Transmitter filtering
tx_shaped = np.convolve(
    impulse_train,
    h_rrc
)

# Receiver matched filtering
rx_output = np.convolve(
    tx_shaped,
    h_rrc
)

# Normalize
rx_output = (
    rx_output
    / np.max(np.abs(rx_output))
)

# Total delay
total_delay = 2 * span * sps


# ================================================================
# 17. PLOT CASCADED RRC RESPONSE
# ================================================================

plt.figure(figsize=(12, 6))

plt.plot(
    np.arange(len(rx_output)) - total_delay,
    rx_output,
    linewidth=1.3,
    label='RRC × RRC'
)

plt.plot(
    t / Ts * sps,
    h_rc,
    '--',
    linewidth=1.2,
    label='Reference RC'
)

plt.xlim([
    -span * sps,
    span * sps
])

plt.xlabel(
    'Sample Index Relative to Center'
)

plt.ylabel('Amplitude')

plt.title(
    'RRC Transmitter + RRC Receiver Cascade'
)

plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 18. CASCADE NYQUIST VERIFICATION
# ================================================================

sample_indices = (
    total_delay
    + n_check * sps
    + 1
)

# Python uses zero-based indexing
sample_indices = sample_indices.astype(int)

valid = (
    (sample_indices >= 0)
    &
    (sample_indices < len(rx_output))
)

cascade_samples = rx_output[
    sample_indices[valid]
]

valid_n = n_check[valid]


print("\n")
print("================================================")
print("RRC CASCADE NYQUIST VERIFICATION")
print("================================================")
print(" n        Cascade Response")
print("-----------------------------------------------")

for n, value in zip(
    valid_n,
    cascade_samples
):

    print(
        f"{n:3d}       {value:+.6f}"
    )


# ================================================================
# 19. BANDWIDTH VS ROLL-OFF FACTOR
# ================================================================

alpha_sweep = np.arange(
    0,
    1.001,
    0.05
)

# Theoretical bandwidth
B_theory = (
    1 + alpha_sweep
) / (2 * Ts)

B_measured = np.zeros(
    len(alpha_sweep)
)


# ================================================================
# 20. MEASURE BANDWIDTH USING FFT
# ================================================================

for i, alpha in enumerate(alpha_sweep):

    hh = raised_cosine(
        t,
        Ts,
        alpha
    )

    H = np.abs(
        np.fft.fftshift(
            np.fft.fft(hh, Nfft)
        )
    )

    H = H / np.max(H)

    positive = f >= 0

    f_positive = f[positive]
    H_positive = H[positive]

    # Find first frequency below 1%
    indices = np.where(
        H_positive < 0.01
    )[0]

    if len(indices) > 0:

        index = indices[0]

    else:

        index = len(f_positive) - 1

    B_measured[i] = f_positive[index]


# ================================================================
# 21. PLOT BANDWIDTH VS ROLL-OFF
# ================================================================

plt.figure(figsize=(10, 6))

plt.plot(
    alpha_sweep,
    B_theory,
    linewidth=1.8,
    label='Theory: (1+α)/(2Ts)'
)

plt.plot(
    alpha_sweep,
    B_measured,
    'o',
    label='Measured using FFT'
)

plt.xlabel(
    'Roll-off Factor α'
)

plt.ylabel(
    'Bandwidth (Hz)'
)

plt.title(
    'Bandwidth vs Roll-Off Factor'
)

plt.legend()
plt.grid(True)

plt.show()


# ================================================================
# 22. FINAL RESULTS
# ================================================================

print("\n")
print("================================================")
print("EXPERIMENT 7 COMPLETED SUCCESSFULLY")
print("================================================")

print("\nKey Results:")
print("1. Rectangular pulse has a sharp time-domain transition.")
print("2. Sinc pulse satisfies the ideal Nyquist criterion.")
print("3. Raised-cosine pulse provides zero ISI.")
print("4. Increasing roll-off factor increases bandwidth.")
print("5. RRC transmitter + RRC receiver gives an RC response.")
print("6. RC pulse has zero crossings at integer multiples of Ts.")
print("================================================")
